MOC_script_path: idi/moc_ec/MOC/scripts/
Key_base: /idi/moc_ec/MOC/Key_files/
Seq_base: /idi/moc_ec/RawSeq_data/SCR/ 
RawSeq_sym_path: /idi/moc_ec/RawSeq_data/SCR/SymLinks/
Temp_path: /broad/hptmp/RNASeq_proj/MOC/
IndSplit_path: /idi/moc_ec/hptmp/RNASeq_proj/MOC/index_split/
Bam_path: /idi/moc_ec/idpweb/data/MOC/
Results_path: /idi/moc_ec/RNASeq_results/MOC/
Transfer_path: /idi/moc_ec/hptmp/MOC/transfer/MOC/
Bacterial_Ref_path: /idi/moc_ec/NCBI_files2/
genbank_ref_path: /idi/moc_ec/MOC/genbank/
gdrivelocal_path: /idi/moc_ec/MOC/MOC_gdrive/
Align_path:  /idi/moc_ec/BactRAP/align/
Walkup_path: /seq/walkup/picard/
qiime_path: /idi/moc_ec/RawSeq_data/16S/16S_results/
stock_log_path: MOC/BMB_strains/BMB_stock_logs/
stock_log_local: /broad/moc/BMB/stock_logs/
sample_plate_map_path: /broad/moc/BMB/sample_maps/
stock_plate_map_path: /broad/moc/BMB/stock_maps/
linked_stock_maps_path: /broad/moc/BMB/linked_stock_maps/
linked_map_out_path: MOC/BMB_strains/linked_maps/
file_path: /idi/moc_ec/MOC/files/

gdrivemoc_path: MOC/IDMP_PC/Production/Projects/
gdrivePC_path:  MOC/IDMP_PC/Production/Projects/ 
gdriveDEV_path:  MOC/IDMP_PC/Development/ 
gdriveGCIDTC_path:  MOC/GCID_TC/Projects/ 
gdriveCIS_path:  MOC/CISID/Projects/ 
gdrivepm_path:  MOC/IDMP_PC/Project_management/

  
#----------------------------
# Most of the time the host can be either mouse or human. It is expected that
# the host reference would be prepated

Suffix_s1: .unmapped.1.fastq
Suffix_s2: .unmapped.2.fastq
Suffix_ne:  _L001_R1_merged.fastq

strand_dir:  reverse 
RtS_dict_file:  /idi/moc_ec/MOC/files/rts_bcs.txt
SCR_dict_file:  /idi/moc_ec/MOC/files/scr_bcs.txt
AllSeq_dict_file:  /idi/moc_ec/MOC/RtS_pipeline/barcodes/allseq_bcs.txt

### KEY_HEADERS_START ###

P7:             Pool_ID
P5:             Index2_seq
Proj:           Project_ID
ID:             Sample_ID
LC_method:      LC_method
bc:             Inline_Seq
Seq_type:       Sequencer
Seq_dir:        Directory
Seq_file:       Path_to_SeqFile
Flowcell:       Flowcell
Lane:           Lane
Ref_accession:  Bacterial_reference
Host_reference: Host_reference
Strain:         Strain_ID
Genus:         Genus
Read_pairing:   Read_pairing
Path_to_SeqFile: Path_to_SeqFile
Key_end: Deviations

### KEY_HEADERS_END ### 
 
Production_prefixes:    MOCP
Dev_prefixes:   RtS
TC_prefixes:    DAB;SWB;ITS;SWG
CIS_prefixes:   SCR;DRS;HPV


#----------------------------------------------------
# This would be the entries that the user should not change,
# unless required.

delim: /

# RtS analysis pipeline
pipeline: idi/moc_ec/MOC/RtS_pipeline/beta/PipelineMain.py
RtS_analysis_pipe: idi/moc_ec/MOC/scripts/MOC_RtS_pipe_v2.sh
P7_barcodes: idi/moc_ec/MOC/files/RtS_i7.txt
P5_barcodes: idi/moc_ec/MOC/files/RtS_i5.txt
DB_script: idi/moc_ec/MOC/scripts/MOC_DB_find.sh
Single_Index_split_script: idi/moc_ec/MOC/RtS_pipeline/BarcodeSplitter/IndexSplitterMain.py
Dual_Index_split_script: idi/moc_ec/MOC/RtS_pipeline/dual_indexed_bc/IndexSplitterMain.py 
qsub_script: idi/moc_ec/MOC/scripts/MOC_QSUB_launch.sh
join_script: idi/moc_ec/MOC/scripts/MOC_KeyMets_Join.sh
poolwise_metrics_script: idi/moc_ec/MOC/scripts/poolwise_metrics.py
join_key_metrics_with_trimmomatic_script: idi/moc_ec/MOC/scripts/join_trimmomatic_and_key_metrics.py
keyfile_importer: idi/moc_ec/MOC/RtS_pipeline/beta/quickstart.py
gs_importer: idi/moc_ec/MOC/scripts/GS_import.sh
wu_movesplit: idi/moc_ec/MOC/scripts/MOC_wu_moveANDsplit.sh
wu_metrics_script: idi/moc_ec/MOC/scripts/MOC_walkup_metrics2.sh
split_metrics_script: idi/moc_ec/MOC/scripts/Split_distribution_metrics2.sh
gdrive_script: /idi/moc_ec/MOC/bin/drive
user_guide:  idi/moc_ec/MOC/files/MOC_RNA-Seq_data_UserGuide_CURRENT.docx
aspera_script: idi/moc_ec/MOC/scripts/Aspera_manifest_maker.sh
manifest_dir: /idi/moc_ec/Aspera_manifests/
join_path: /idi/moc_ec/MOC/MKJoin_files/
edgeR_script: idi/moc_ec/MOC/scripts/edgeR_main.R
deseq_script: idi/moc_ec/MOC/scripts/DESeq_launch6.sh
DE_pipe: idi/moc_ec/MOC/scripts/Key_DE_launch2.sh
Checksum_script: idi/moc_ec/MOC/scripts/RawSeq_checksum.sh
gff_parse_script: idi/moc_ec/MOC/RtS_pipeline/beta/shell_scripts/gff_parse5.sh
ref_move_parse_script: idi/moc_ec/MOC/scripts/MOC_ref_fetch_and_parse.sh
symlink_script: idi/moc_ec/MOC/scripts/RawSeq_SymLink.sh
orphan_script:  idi/moc_ec/MOC/scripts/dual_orphan_find.sh
check_module_script: idi/moc_ec/MOC/scripts/check_RtS_module.sh
wbmov_metrics_script: idi/moc_ec/MOC/scripts/MOCS_move.sh
report_script: idi/moc_ec/MOC/scripts/KeyMetrics_report.sh
bash_header: idi/moc_ec/MOC/scripts/bash_header

pipe_script_dir: idi/moc_ec/MOC/RtS_pipeline/beta/
bc_splitter: idi/moc_ec/MOC/RtS_pipeline/BarcodeSplitter/bc_splitter
dict_builder: idi/moc_ec/MOC/RtS_pipeline/BarcodeSplitter/dict_builder
bc_splitter: idi/moc_ec/MOC/RtS_pipeline/beta//bc_splitter
bc_splitter_rts: idi/moc_ec/MOC/RtS_pipeline/BarcodeSplitter/bc_splitter_rts
bc_splitter_rts_se: idi/moc_ec/MOC/RtS_pipeline/BarcodeSplitter/bc_splitter_rts_se
bc_splitter_scr: idi/moc_ec/MOC/RtS_pipeline/BarcodeSplitter/bc_splitter_scr
sam_fragcount: idi/moc_ec/MOC/RtS_pipeline/read_counter/sam_fragcount
frag_to_gene_count: idi/moc_ec/MOC/RtS_pipeline/read_counter/frag_to_gene_count
metrics_gen: idi/moc_ec/MOC/RtS_pipeline/read_counter/metrics_gen
split_plot_path:  idi/moc_ec/MOC/RtS_pipeline/BarcodeSplitter/plot_dist.R
bwa: broad/IDP-Dx_work/nirmalya/local/bin/bwa
samtools: broad/IDP-Dx_work/nirmalya/local/bin/samtools
rsem-prepare-reference: broad/IDP-Dx_work/nirmalya/local/bin/rsem-prepare-reference
rsem-calculate-expression: broad/IDP-Dx_work/nirmalya/local/bin/rsem-calculate-expression
salmon: broad/IDP-Dx_work/nirmalya/local/bin/salmon
featureCounts: broad/IDP-Dx_work/nirmalya/local/bin/featureCounts
cutadapt: broad/IDP-Dx_work/nirmalya/local/bin/cutadapt
JLCounter: idi/moc_ec/MOC/RtS_pipeline/beta/shell_scripts/SAM_to_counts2.sh
picard_bindir: broad/IDP-Dx_work/nirmalya/tools/picard/latest
AllSeq_read_trim: idi/moc_ec/MOC/RtS_pipeline/rust_code/allseq_read_trim/target/release/AllSeq_read_trim
UGER_cbp: broad/IDP-Dx_work/nirmalya/tools/ugetools/UGE_SUBMISSIONS/UGER_cmd_batch_processor.py
patho_dbpath: /idi/moc_ec/NCBI_files2/
host_dbpath: /home/unix/hsethura/fungal/
STAR: broad/IDP-Dx_work/nirmalya/tools/bin/STAR
tdf_str:  /broad/IDP-Dx_storage/BactRAP/scripts/bam2tdf-14/bam2tdf.jar
human_ref_str:  Human_hg38
mouse_ref_str:  Mouse_mm10
fungal_ref_str: fungal
candida_albicans_ref_str: candida_albicans_SC5314
bbmap_path: broad/IDP-Dx_work/nirmalya/local/bin/bbmap.sh 
trimmomatic_jar: idi/moc_ec/MOC/Trimmomatic-0.39/trimmomatic-0.39.jar
trimmomatic_stats_script: idi/moc_ec/MOC/Trimmomatic-0.39/trimmomatic_stats.sh
read_insertion_adapter_analysis_script: idi/moc_ec/MOC/RtS_pipeline/read_insertions_in_adapter/process_blast_output.py

# adapters for Trimmomatic
rts_trimmomatic_adapter_file: idi/moc_ec/MOC/Trimmomatic-0.39/adapters/RtS_adapters.fasta
scr_trimmomatic_adapter_file: idi/moc_ec/MOC/Trimmomatic-0.39/adapters/SCR_adapters.fasta

# adapters for Read insertions in adapter analysis
rts_adapter_analysis_adapter_file: idi/moc_ec/MOC/RtS_pipeline/read_insertions_in_adapter/rts_adapters.fasta
scr_adapter_analysis_adapter_file: idi/moc_ec/MOC/RtS_pipeline/read_insertions_in_adapter/scr_adapters.fasta

# thread count and memory for host side alignment:q
patho_thread_count: 1
patho_memory: 8
host_thread_count: 4
host_memory: 8
mouse_transcript_gene: /broad/IDP-Dx_storage/Host_reference/data/Mouse_mm10_transcript_gene.txt
human_transcript_gene: /broad/IDP-Dx_storage/Host_reference/data/Human_hg38_transcript_gene.txt
fungal_transcript_gene: /home/unix/hsethura/fungal/data/fungal_transcript_gene.txt
candida_albicans_SC5314_transcript_gene: /home/unix/hsethura/fungal/data/candida_albicans_SC5314_transcript_gene_transcript_gene.txt

### paths to pipeline scripts

Pipeline_bcLog: idi/moc_ec/MOC/RtS_pipeline/beta/shell_scripts/Pipeline_bcLog.sh
corr_script: idi/moc_ec/MOC/RtS_pipeline/beta/rscripts/corr2.R
gff_parser: idi/moc_ec/MOC/RtS_pipeline/beta/shell_scripts/gff_parse4.sh
RPG_metrics_script: idi/moc_ec/MOC/RtS_pipeline/beta/shell_scripts/RPG_metrics5.sh
RPG_drop_metrics_script: idi/moc_ec/MOC/RtS_pipeline/beta/shell_scripts/RPG_drop_metrics.sh
Data_finish_script: idi/moc_ec/MOC/RtS_pipeline/beta/shell_scripts/Data_finish.sh
bcLog_metrics_script: idi/moc_ec/MOC/scripts/Pipeline_bcLog.sh
trim_script: idi/moc_ec/MOC/RtS_pipeline/beta/shell_scripts/fastq_trim2.sh
picard_metrics: idi/moc_ec/MOC/RtS_pipeline/beta/shell_scripts/PICARD_metrics.sh
picard_metrics_parse: idi/moc_ec/MOC/RtS_pipeline/beta/shell_scripts/PICARD_metrics_parse.sh
fpkm_script: idi/moc_ec/MOC/scripts/counts_to_FPKMO.sh
bestacc_script: idi/moc_ec/MOC/RtS_pipeline/beta/shell_scripts/Pipeline_bestAcc2.sh

